FROM node:22

WORKDIR /usr/local/app

# Installer dépendances (cache optimisé)
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Donner les droits à l'utilisateur node
RUN chown -R node:node /usr/local/app

# Switch utilisateur
USER node

# Code monté via watch

CMD ["npm", "run", "dev"]