FROM node:24-bookworm

WORKDIR /usr/local/app

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm install

RUN chown -R node:node /usr/local/app
USER node

CMD ["npm", "run", "dev"]