apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: todo-app
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api-deployment
          image: nicoareregistrytodoapp.azurecr.io/backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: production

            - name: KAFKA_BROKER
              value: kafka:9092

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: MYSQL_USER_API

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: MYSQL_PASSWORD_API

            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: MYSQL_HOST_API

            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: MYSQL_DB_API

            - name: MYSQL_SSL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: MYSQL_SSL
                  optional: true

          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"

          livenessProbe:
            httpGet:
              path: /api/greeting
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/greeting
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
