apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apidb-pvc
  namespace: todo-app
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
