resources:
  - namespace.yaml

  - secret.yaml
  - configmap.yaml
  - kafka-configmap.yaml
  - nginx-configmap.yaml

  - apidb-pvc.yaml
  - apidb-deployment.yaml
  - apidb-service.yaml

  - api-deployment.yaml
  # - api-autoscale.yaml
  - api-service.yaml

  - kafka-deployment.yaml
  - kafka-service.yaml

  # - angular-deployment.yaml
  # - angular-autoscale.yaml
  # - angular-service.yaml

  - nginx-deployment.yaml
  - nginx-service.yaml
