apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: todo-app
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream frontend {
        # These are references to our backend containers, facilitated by
        # Compose, as defined in docker-compose.yml
        server client-service:80;
      } 
      upstream backend {
        # These are references to our backend containers, facilitated by
        # Compose, as defined in docker-compose.yml
        server api-service:3000;
      }
      upstream auth {
        # These are references to our auth containers, facilitated by
        # Compose, as defined in docker-compose.yml
        server auth-service:3001;
      }
      

    server {
        listen 80;
        server_name frontend;
        server_name backend;
        server_name auth;

        location / {
          resolver kube-dns.kube-system.svc.cluster.local valid=30s;
          proxy_pass http://frontend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
          resolver kube-dns.kube-system.svc.cluster.local valid=30s;
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location /auth {
          resolver kube-dns.kube-system.svc.cluster.local valid=30s;
          proxy_pass http://auth;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

      }
    }
