apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: todo-secret
  namespace: todo-app
stringData:
  # backend
  MYSQL_USER_API: "todoadmin"
  MYSQL_PASSWORD_API: "TodoApp2024!"

  # auth
  MYSQL_USER_AUTH: "todoadmin"
  MYSQL_PASSWORD_AUTH: "TodoApp2024!"
