apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: todo-secret
  namespace: todo-app
stringData:
  # backend
  MYSQL_USER_API: "user_api"
  MYSQL_PASSWORD_API: "password_api"

  # auth
  MYSQL_USER_AUTH: "user_auth"
  MYSQL_PASSWORD_AUTH: "password_auth"
