name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache client deps
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: client-${{ hashFiles('client/package-lock.json') }}

      - name: Install deps
        run: |
          cd client
          npm install

      - name: Lint
        run: |
          cd client
          npm run lint

      - name: Build
        run: |
          cd client
          npm run build

      - name: Unit tests
        run: |
          cd client
          npm test tests/unit


  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache backend deps
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: backend-${{ hashFiles('backend/package-lock.json') }}

      - name: Install deps
        run: |
          cd backend
          npm install

      # - name: Build
      #   run: |
      #     cd backend
      #     npm run build

      - name: Unit tests
        run: |
          cd backend
          npm test