name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    outputs:
      client: ${{ steps.filter.outputs.client }}
      backend: ${{ steps.filter.outputs.backend }}
      auth: ${{ steps.filter.outputs.auth }}
      pipeline: ${{ steps.filter.outputs.pipeline }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
            backend:
              - 'backend/**'
            auth:
              - 'auth/**'
            pipeline:
              - '.github/workflows/**'
          token: ${{ secrets.GITHUB_TOKEN }}


  client:
    needs: changes
    if: |
      needs.changes.outputs.client == 'true' ||
      needs.changes.outputs.pipeline == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache client deps
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: client-${{ hashFiles('client/package-lock.json') }}

      - name: Install deps
        run: |
          cd client
          npm install

      - name: Lint
        run: |
          cd client
          npm run lint

      - name: Build
        run: |
          cd client
          npm run build

      - name: Unit tests
        run: |
          cd client
          npm test tests/unit

      - name: Integration tests
        if: github.event_name == 'pull_request' 
        run: |
          cd client
          npm run test tests/integrations


  backend:
    needs: changes
    if: |
      needs.changes.outputs.backend == 'true' ||
      needs.changes.outputs.pipeline == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        run: cd backend && npm ci

      - name: Lint
        run: cd backend && npm run lint

      - name: Build
        run: cd backend && npm run build

      - name: Unit tests
        run: cd backend && npm test

      - name: Integration tests
        if: github.event_name == 'pull_request'
        run: cd backend && npm test integrations


  auth:
    needs: changes
    if: |
        needs.changes.outputs.auth == 'true' ||
        needs.changes.outputs.pipeline == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: auth/package-lock.json

      - name: Install deps
        run: cd auth && npm ci

      - name: Lint
        run: cd auth && npm run lint

      - name: Build
        run: cd auth && npm run build

      - name: Unit tests
        run: cd auth && npm test

      - name: Integration tests
        if: github.event_name == 'pull_request'
        run: cd auth && npm test integrations


  docker-client:
    runs-on: ubuntu-latest
    needs: [client]

    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name : Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: nicoareregistrytodoapp.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push client
        uses: docker/build-push-action@v7
        with:
          context: ./client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            nicoareregistrytodoapp.azurecr.io/client:${{ github.sha }}
            nicoareregistrytodoapp.azurecr.io/client:latest

  docker-backend:
    runs-on: ubuntu-latest
    needs: [backend]

    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name : Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: nicoareregistrytodoapp.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            nicoareregistrytodoapp.azurecr.io/backend:${{ github.sha }}
            nicoareregistrytodoapp.azurecr.io/backend:latest

  docker-auth:
    runs-on: ubuntu-latest
    needs: [auth]

    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name : Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: nicoareregistrytodoapp.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push auth
        uses: docker/build-push-action@v7
        with:
          context: ./auth
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            nicoareregistrytodoapp.azurecr.io/auth:${{ github.sha }}
            nicoareregistrytodoapp.azurecr.io/auth:latest